### ISSUE TITLE
Issue with new version of numpy

### ISSUE THREAD

**Issue by wibuf** [coffecup25/FishyFishing#1]
The bot does the cast successfully and starts reeling in, however on the first color difference check it throws an error:

`Traceback (most recent call last):
  File "C:\fishp\main.py", line 205, in <module>
    main()
  File "C:\fishp\main.py", line 53, in main
    bait()
  File "C:\fishp\main.py", line 155, in bait
    diff=difference(color,LOWER_BAR_RGB)
  File "C:\fishp\main.py", line 170, in difference
    return delta_e_cie2000(color_a_lab,color_b_lab)
  File "C:\Users\STi\AppData\Local\Programs\Python\Python39\lib\site-packages\colormath\color_diff.py", line 79, in delta_e_cie2000
    return numpy.asscalar(delta_e)
  File "C:\Users\STi\AppData\Local\Programs\Python\Python39\lib\site-packages\numpy\__init__.py", line 311, in __getattr__
    raise AttributeError("module {!r} has no attribute "
AttributeError: module 'numpy' has no attribute 'asscalar'`

**Comment by coffecup25** [comment]
imma be honest, I never thought anyone would use this ahahah
But it should be an easy fix

**Comment by wibuf** [comment]
lol, you don't have to update it, I was able to revert to numpy 1.15.4 and it works okay for the most part. I've been going through the code cause I think what resolution the game is set to affects the locations of the boxes it checks for color changes. If you happen to know what resolution you wrote this for please let me know, doesn't seem to be 1920x1080. Thanks

**Comment by coffecup25** [comment]
Hmmm looking the size of the screenshot it was 1920x1080 but I guess they've changed the UI layout

**Comment by wibuf** [comment]
That makes sense, everything works besides the fish on detection. If I'm able to get a version working again I'll send an update. 

Thanks for your help

**Comment by coffecup25** [comment]
Ahahah no worries! Just glad someone found this

**Comment by coffecup25** [comment]
But with "fish on detection" you mean it doesn't register when there's a fish on the hook?

**Comment by wibuf** [comment]
Yeah exactly, it casts fine, then starts a reel in, but line 161:
`if diff<THRESHOLD:`

Is never hit because I think all these coordinates are no longer correct:

```
BAR_BOT_LEFT = (1765,880)
BAR_BOT_RIGHT = (1817,880)
BAR_TOP_LEFT = (1765,467)
BAR_TOP_RIGHT = (1817,467)

THRESHOLD = 3.5

BAR_LEFT_X=1770
BAR_RIGHT_X=1813

LOWER_BAR_RGB = sRGBColor(23/255.0, 168/255.0, 195/255.0)
LOWER_BAR_TOP_Y=842
LOWER_BAR_BOT_Y=835

HIGHER_BAR_RGB = (27/255.0, 171/255.0, 179/255.0)
HIGHER_BAR_TOP_Y=820
HIGHER_BAR_BOT_Y=828

DISTANCE_BOX=(1520, 925, 1630, 1001)
```

Currently trying to figure out the best way of correcting these.

**Comment by coffecup25** [comment]
So they way I did it was take a screenshot, open it in a photo editor and note down the coordinates of the cursor for the boxes that are needed
